# GitHub actions workflow.
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

name: Build CI

on:
  push:
    branches: [master, fix-*, feat-*, appimage]
    tags: [v*]
  pull_request:
    types: [opened]
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        cc: [gcc]
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
    steps:
    - run: sudo apt-get update -y
    - run: sudo apt-get install -y libgtkmm-3.0-dev libcurl4-gnutls-dev libyajl-dev valgrind
    - uses: actions/checkout@v3
    - run: make
    - run: sudo make install
    - run: make clean
    - run: which samrewritten
    - run: package/build_appimage.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: SamRewritten
        path: package/**.AppImage 
